package user;

import controle.frm_login;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor e Mariane
 * Mari Vek Histories
 */

public class frm_catalogo extends javax.swing.JFrame {

    int id;
    String nome;
    String usuario;
    String nasc;
    
    /**
     * Creates new form Catalogo
     */
    public frm_catalogo(int realId, String realUser, String realNome, String realNasc) {
        initComponents();
        initVariables(realId, realUser, realNome, realNasc);
        getContentPane().setBackground(Color.black);
        icone();
    }

    private void initVariables(int realId, String realUser, String realNome, String realNasc){
        id = realId;
        nome = realNome;
        nasc = realNasc;
        usuario = realUser;
    }
    
    
    private void icone(){
        //método que traz a imagem na raiz do projeto
        //método getClass e getResourse são para puxar a imagem no arquivo .jar 
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/icones/icon.png"));
        //método que redimensiona a imagem
        Image scaleImage = imageIcon.getImage().getScaledInstance(25, 25,Image.SCALE_DEFAULT);
        //método que traz a imagem dimensionada
        ImageIcon img = new ImageIcon(scaleImage);
        
        this.setIconImage(img.getImage());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnFilmeDois = new javax.swing.JButton();
        btnFilmeTres = new javax.swing.JButton();
        btnFilmeQuatro = new javax.swing.JButton();
        btnFilmeCinco = new javax.swing.JButton();
        btnFilmeSeis = new javax.swing.JButton();
        btnFilmeSete = new javax.swing.JButton();
        btnFilmeOito = new javax.swing.JButton();
        btnFilmeNove = new javax.swing.JButton();
        btnFilmeDez = new javax.swing.JButton();
        btnFilmeOnze = new javax.swing.JButton();
        btnFilmeDoze = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btnFilmeUm = new javax.swing.JButton();
        lblRomance = new javax.swing.JLabel();
        lblTerror = new javax.swing.JLabel();
        lblAcao = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        welcome1 = new javax.swing.JLabel();
        lblLoc = new javax.swing.JLabel();
        lblcount = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Javaflix(Catálogo de Filmes)");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Panel.setBackground(new java.awt.Color(0, 51, 51));
        Panel.setPreferredSize(new java.awt.Dimension(700, 715));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("CATÁLOGO");

        btnFilmeDois.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeDois.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/6.png"))); // NOI18N
        btnFilmeDois.setToolTipText("Titanic");
        btnFilmeDois.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFilmeDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmeDoisActionPerformed(evt);
            }
        });

        btnFilmeTres.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeTres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/7.png"))); // NOI18N
        btnFilmeTres.setToolTipText("O Melhor Amigo da Noiva");
        btnFilmeTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnFilmeQuatro.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeQuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/8.png"))); // NOI18N
        btnFilmeQuatro.setToolTipText("Sociedade Literária");
        btnFilmeQuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFilmeQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmeQuatroActionPerformed(evt);
            }
        });

        btnFilmeCinco.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/1.png"))); // NOI18N
        btnFilmeCinco.setToolTipText("A Noiva-Cadáver");
        btnFilmeCinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFilmeCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmeCincoActionPerformed(evt);
            }
        });

        btnFilmeSeis.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeSeis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/2.png"))); // NOI18N
        btnFilmeSeis.setToolTipText("Casa Monstro");
        btnFilmeSeis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnFilmeSete.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeSete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/4.png"))); // NOI18N
        btnFilmeSete.setToolTipText("Invocação do Mal");
        btnFilmeSete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnFilmeOito.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeOito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/11.png"))); // NOI18N
        btnFilmeOito.setToolTipText("The Batman");
        btnFilmeOito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnFilmeNove.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeNove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/9.png"))); // NOI18N
        btnFilmeNove.setToolTipText("Motoqueiro Fantasma");
        btnFilmeNove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnFilmeDez.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeDez.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/3.png"))); // NOI18N
        btnFilmeDez.setToolTipText("Coraline e o Mundo Secreto");
        btnFilmeDez.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnFilmeOnze.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeOnze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/10.png"))); // NOI18N
        btnFilmeOnze.setToolTipText("Clube da Luta");
        btnFilmeOnze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnFilmeDoze.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeDoze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/12.png"))); // NOI18N
        btnFilmeDoze.setToolTipText("Em Ritmo de Fuga");
        btnFilmeDoze.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton11.setText(";)");

        btnFilmeUm.setBackground(new java.awt.Color(0, 0, 0));
        btnFilmeUm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/5.png"))); // NOI18N
        btnFilmeUm.setToolTipText("Orgulho e Preconceito");
        btnFilmeUm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblRomance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRomance.setForeground(new java.awt.Color(255, 255, 255));
        lblRomance.setText("Romance");

        lblTerror.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTerror.setForeground(new java.awt.Color(255, 255, 255));
        lblTerror.setText("Terror");

        lblAcao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAcao.setForeground(new java.awt.Color(255, 255, 255));
        lblAcao.setText("Ação");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(lblRomance)
                        .addGap(184, 184, 184)
                        .addComponent(lblTitulo))
                    .addComponent(lblAcao)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(btnFilmeNove)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilmeOnze)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilmeOito)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilmeDoze))
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(btnFilmeCinco)
                                .addGap(18, 18, 18)
                                .addComponent(btnFilmeSeis)
                                .addGap(18, 18, 18)
                                .addComponent(btnFilmeDez)
                                .addGap(18, 18, 18)
                                .addComponent(btnFilmeSete))
                            .addComponent(lblTerror))
                        .addGroup(PanelLayout.createSequentialGroup()
                            .addComponent(btnFilmeUm)
                            .addGap(18, 18, 18)
                            .addComponent(btnFilmeDois)
                            .addGap(18, 18, 18)
                            .addComponent(btnFilmeTres)
                            .addGap(18, 18, 18)
                            .addComponent(btnFilmeQuatro))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblRomance)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFilmeDois)
                    .addComponent(btnFilmeTres)
                    .addComponent(btnFilmeQuatro)
                    .addComponent(btnFilmeUm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTerror)
                .addGap(1, 1, 1)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFilmeSeis)
                    .addComponent(btnFilmeCinco)
                    .addComponent(btnFilmeDez)
                    .addComponent(btnFilmeSete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAcao)
                .addGap(1, 1, 1)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFilmeOnze)
                    .addComponent(btnFilmeOito)
                    .addComponent(btnFilmeNove)
                    .addComponent(btnFilmeDoze))
                .addGap(183, 183, 183)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logoLocadora.png"))); // NOI18N

        lbluser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbluser.setForeground(new java.awt.Color(227, 4, 25));
        lbluser.setText("null");

        welcome1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        welcome1.setForeground(new java.awt.Color(227, 4, 25));
        welcome1.setText("Olá,");

        lblLoc.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblLoc.setForeground(new java.awt.Color(227, 4, 25));
        lblLoc.setText("Filmes Alugados");
        lblLoc.setToolTipText("Ver os filmes que aluguei");
        lblLoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLocMouseExited(evt);
            }
        });

        lblcount.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblcount.setForeground(new java.awt.Color(227, 4, 25));
        lblcount.setText("Minha Conta");
        lblcount.setToolTipText("Ver informações da minha conta");
        lblcount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblcount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcountMouseExited(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(227, 4, 25));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/door_in.png"))); // NOI18N
        btnExit.setToolTipText("Sair da sua conta");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLoc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnExit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblcount)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(welcome1)
                                    .addComponent(lbluser))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(welcome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbluser)
                .addGap(67, 67, 67)
                .addComponent(lblLoc)
                .addGap(18, 18, 18)
                .addComponent(lblcount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilmeCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmeCincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilmeCincoActionPerformed

    private void btnFilmeQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmeQuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilmeQuatroActionPerformed

    private void btnFilmeDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmeDoisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilmeDoisActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lbluser.setText(nome + "!");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lbluser.setText(nome + "!");
    }//GEN-LAST:event_formWindowActivated

    private void lblLocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocMouseClicked
        frm_view_loc mostra = new frm_view_loc(id, usuario, nome, nasc);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblLocMouseClicked

    private void lblLocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocMouseEntered
        lblLoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLoc.setFont(new java.awt.Font("Tahoma", 1, 19));
        lblLoc.setText("<html><u>Filmes Alugados</u></html>");
    }//GEN-LAST:event_lblLocMouseEntered

    private void lblLocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLocMouseExited
        lblLoc.setFont(new java.awt.Font("Tahoma", 0, 22));
    }//GEN-LAST:event_lblLocMouseExited

    private void lblcountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcountMouseEntered
        lblcount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblcount.setFont(new java.awt.Font("Tahoma", 1, 19));
        lblcount.setText("<html><u>Minha Conta</u></html>");
    }//GEN-LAST:event_lblcountMouseEntered

    private void lblcountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcountMouseClicked
        frm_user_count mostra = new frm_user_count(id, usuario, nome, nasc);
        mostra.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblcountMouseClicked

    private void lblcountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcountMouseExited
        lblcount.setFont(new java.awt.Font("Tahoma", 0, 22));
    }//GEN-LAST:event_lblcountMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja sair da sua conta? ","Logout", JOptionPane.YES_NO_OPTION, 3);
            
        if (resposta == 0){
            frm_login mostra = new frm_login();
            mostra.setVisible(true);
            dispose();
        }
        else{
            
        }
    }//GEN-LAST:event_btnExitActionPerformed
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int a = 0;
                String b = "";
                String c = "";
                String d = "";
                new frm_catalogo(a, b, c, d).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFilmeCinco;
    private javax.swing.JButton btnFilmeDez;
    private javax.swing.JButton btnFilmeDois;
    private javax.swing.JButton btnFilmeDoze;
    private javax.swing.JButton btnFilmeNove;
    private javax.swing.JButton btnFilmeOito;
    private javax.swing.JButton btnFilmeOnze;
    private javax.swing.JButton btnFilmeQuatro;
    private javax.swing.JButton btnFilmeSeis;
    private javax.swing.JButton btnFilmeSete;
    private javax.swing.JButton btnFilmeTres;
    private javax.swing.JButton btnFilmeUm;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAcao;
    private javax.swing.JLabel lblLoc;
    private javax.swing.JLabel lblRomance;
    private javax.swing.JLabel lblTerror;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblcount;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel welcome1;
    // End of variables declaration//GEN-END:variables
}
